### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by hugodecasta** [AdrienJarretier/visualisation-cas-covid-19#15]
The master branch's npm start is (console log apparently) listening to 3000 but the systems does not answer to browser requests

**Comment by AdrienJarretier** [comment]
Works fine for me and on the prod server.

I'll need some information, on the browser used,

check the requests responses in the browser too , see if there are requests without a 200 status response.

**Comment by hugodecasta** [comment]
I use an inner proxy calling a linux VM with its own local network, the input host is not 127.0.0.1
The [listening interface](https://github.com/AdrienJarretier/visualisation-cas-covid-19/blob/master/bin/www#L44) system cannot listen to my proxy adress calling.

**Comment by hugodecasta** [comment]
I thinck the reason why the prod server works is because of an inner re-routing resulting in calls from host 127.0.0.1

**Comment by AdrienJarretier** [comment]
oh yeah that's probably the issue. By default, you can see it in config.json, the server only binds to 127.0.0.1, you can change it to 0.0.0.0, so it will listen on all interfaces.

On the prod server apache is proxying.

**Comment by hugodecasta** [comment]
Yep I understand but the question is should we commit a 0.0.0.0 listener or leave the localhost listener ?

**Comment by AdrienJarretier** [comment]
> 
> 
> Yep I understand but the question is should we commit a 0.0.0.0 listener or leave the localhost listener ?



https://github.com/AdrienJarretier/visualisation-cas-covid-19/commit/c1368c570efe17633cddafdce4424f4379c5155a#commitcomment-38151034


> 
> 
> No you should not commit that, keep that change locally, but on prod the server should only listen locally to prevent direct access
