### ISSUE TITLE
db update script

### ISSUE THREAD

**Issue by hugodecasta** [AdrienJarretier/visualisation-cas-covid-19#9]
### Affected systems
 - db
### Requests
 - Create an updating db script (calling the updateDb.js script)
 - Load this script on server start
### Advices
 - Use interval or some sort of cron like system to update every morning or night (once every day)

**Comment by AdrienJarretier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [db update script](https://trello.com/c/D6NcBHb3/3-db-update-script)
